### ISSUE TITLE
train.py -> function check_accuracy -> accuracy formula is wrong

### ISSUE THREAD

**Issue by MarkusKoenig73** [yangsiyu007/SpaceNetExploration#2]
need to fix this way:
        acc = float(num_correct) / num_samples / ( preds.size(1)*preds.size(2))
        
        logging.info('number of samples %d, accuracy (perc.) (%.2f)' % ( num_samples, 100 * acc))

**Comment by yangsiyu007** [comment]
Thank you Markus. In the refactored version I'll change it to 
`accuracy = (y == preds).float().mean()`, averaging over all samples in the batch and all pixels. I'll merge the refactored version (currently on branch `batchai`) in the coming weeks.

**Comment by yangsiyu007** [comment]
Merged.
